/**
 * Pi Image Generation Extension
 *
 * Registers a `generate_image` tool that calls OpenRouter image generation API,
 * saves the result to /tmp, and returns path + metadata to the agent.
 */

import { readFileSync } from "node:fs";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { generateImageApi } from "./api";
import { validateImage } from "./validate";
import { saveImageToTemp } from "./save";
import { renderCall, renderResult } from "./render";

export { generateImageApi } from "./api";
export { saveImageToTemp } from "./save";
export type { GenerateImageApiResult } from "./api";
export type { SaveImageResult } from "./save";

const DEFAULT_MODEL_FAST = "google/gemini-3.1-flash-image-preview";
const DEFAULT_MODEL_BEST = "google/gemini-3-pro-image-preview";

const GenerateImageParams = Type.Object({
  prompt: Type.String({
    description: "Text description of the image to generate",
  }),
  quality: Type.Optional(
    Type.String({
      description: "Image quality: 'fast' or 'best' (default: 'fast')",
    }),
  ),
  aspect_ratio: Type.Optional(
    Type.String({
      description:
        "Aspect ratio, e.g. '1:1', '16:9' (default: detected from source image when editing, '1:1' when generating)",
    }),
  ),
  image_path: Type.Optional(
    Type.String({
      description:
        "Path to an existing image file to edit. When provided, the image is sent as context and the tool modifies it based on the prompt.",
    }),
  ),
});

interface ExecuteParams {
  prompt: string;
  quality?: "fast" | "best";
  aspect_ratio?: string;
  image_path?: string;
}

/**
 * Compute the greatest common divisor of two positive integers.
 */
function gcd(a: number, b: number): number {
  a = Math.abs(a);
  b = Math.abs(b);
  while (b) {
    [a, b] = [b, a % b];
  }
  return a;
}

/**
 * Compute a simplified aspect ratio string from width and height.
 * E.g., 1920x1080 → "16:9", 1000x1000 → "1:1", 4x3 → "4:3".
 */
function computeAspectRatio(width: number, height: number): string {
  const divisor = gcd(width, height);
  return `${width / divisor}:${height / divisor}`;
}

export default function (pi: ExtensionAPI): void {
  pi.registerTool({
    name: "generate_image",
    label: "Generate Image",
    description:
      "Generate or edit an image via OpenRouter image generation API. " +
      "Provide a text prompt and optionally image_path to edit an existing image. " +
      "Optional quality (fast/best) and aspect_ratio params. " +
      "Returns path + metadata to the agent.",
    parameters: GenerateImageParams,

    renderCall,
    renderResult,

    async execute(
      _toolCallId: string,
      params: ExecuteParams,
      _signal: AbortSignal,
      _onUpdate: (update: any) => void,
      _ctx: any,
    ) {
      const quality = params.quality || "fast";
      const model =
        quality === "best"
          ? process.env.IMAGE_MODEL_BEST || DEFAULT_MODEL_BEST
          : process.env.IMAGE_MODEL_FAST || DEFAULT_MODEL_FAST;

      // ── Image editing path (image_path provided) ───────────────────────
      if (params.image_path) {
        const { type, width, height } = validateImage(params.image_path);
        const aspectRatio = params.aspect_ratio || computeAspectRatio(width, height);
        const imageBuffer = readFileSync(params.image_path);
        const imageMimeType = `image/${type === "jpg" ? "jpeg" : type}`;

        const result = await generateImageApi(
          params.prompt,
          model,
          aspectRatio,
          imageBuffer,
          imageMimeType,
        );

        if (result.images.length === 0) {
          throw new Error("No images generated by the model");
        }

        const image = result.images[0];
        const saved = saveImageToTemp(image.data, image.mimeType);

        return {
          content: [
            {
              type: "text" as const,
              text: `Edited image saved to ${saved.path}`,
            },
            { type: "image" as const, data: image.data, mimeType: image.mimeType },
          ],
          details: {
            model,
            aspectRatio,
            sizeBytes: saved.sizeBytes,
            path: saved.path,
            sourcePath: params.image_path,
          },
        };
      }

      // ── Generate path (no image_path) ──────────────────────────────────
      const aspectRatio = params.aspect_ratio || "1:1";

      const result = await generateImageApi(params.prompt, model, aspectRatio);

      if (result.images.length === 0) {
        throw new Error("No images generated by the model");
      }

      const image = result.images[0];
      const saved = saveImageToTemp(image.data, image.mimeType);

      return {
        content: [
          { type: "text" as const, text: `Generated image saved to ${saved.path}` },
          { type: "image" as const, data: image.data, mimeType: image.mimeType },
        ],
        details: {
          model,
          aspectRatio,
          sizeBytes: saved.sizeBytes,
          path: saved.path,
        },
      };
    },
  });
}
