version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    networks:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d

networks:
  mysql:
