[tools]
age = "latest"
bun = "latest"
claude = "latest"
fnox = "latest"
"github:ogulcancelik/herdr" = "latest"
jj = "latest"
jjui = "latest"
pi = "0.73.0"
pitchfork = "latest"
tree-sitter = "latest"
uv = "latest"

[settings]
experimental = true
