[tools]
age = "latest"
bun = "latest"
claude = "latest"
fnox = "latest"
"github:ogulcancelik/herdr" = "latest"
jj = "latest"
jjui = "latest"
pi = "0.75.4"
pitchfork = "latest"
tree-sitter = "latest"
uv = "latest"
prettier = "latest"
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:astral-sh/ruff" = "latest"
taplo = "latest"
"aqua:mvdan/sh" = "latest"

[settings]
experimental = true
