require("config.lazy")

require("config.filetypes")
require("config.settings")
require("config.mappings")
require("config.lsp")
require("config.diagnostic")
pcall(function()
	require("custom-settings")
end)
