services:
  audiobookshelf:
    restart: unless-stopped
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /var/stash2/media/Audiobooks:/audiobooks:ro
      - /var/stash2/audiobookshelf:/config
      - /var/stash2/audiobookmeta:/metadata

networks:
  default:
    external: true
    name: nginx
