version: '3.3'
services:
  transmission-openvpn:
    container_name: transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /stash2/media/:/data
      - /stash/media/:/data2
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ
      - OPENVPN_PROVIDER
      - OPENVPN_USERNAME
      - OPENVPN_PASSWORD
      - OPENVPN_CONFIG=default
      - VPN_LOG_LEVEL=11
      - LOCAL_NETWORK
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8118
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_PEER_PORT
      - CREATE_TUN_DEVICE=false
      - TRANSMISSION_WEB_UI=combustion
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
      - '8118:8118'
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
