version: '3.3'
services:
  transmission-openvpn:
    container_name: transmission
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /stash2/media/:/data
      - /stash/media/:/data2
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_USERNAME
      - OPENVPN_PASSWORD=m
      - OPENVPN_CONFIG=nl_all
      - LOCAL_NETWORK=192.168.2.0/24
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8118
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_PEER_PORT=55749
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
      - '8118:8118'
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
