services:
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    volumes:
      - /var/stash2/config:/config:U,z
      - /var/stash2/cache:/cache:U,z
      - /var/stash2/media:/media:ro,z
      - /var/stash/media:/media2:ro,z
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900/udp
      - 7359:7359/udp
      - 18800:18800

networks:
  default:
    external: true
    name: nginx
