#!/bin/bash
alias vi=nvim
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Homebrew package tracking
alias brewsync="bash ~/.dotfiles/homebrew/brew-sync.sh"
alias brewfile="nvim ~/.dotfiles/homebrew/Brewfile"
