export EXA_API_KEY='{{ pass://API/Exa/api_key }}'
export CONTEXT7_API_KEY='{{ pass://API/Context7/api_key }}'
export VENICE_API_KEY='{{ pass://API/Venice/api_key }}'
export CODESTRAL_API_KEY='{{ pass://API/Codestral/api_key }}'
export MINIMAX_API_KEY='{{ pass://API/MiniMax/api_key }}'
export ZAI_API_KEY='{{ pass://API/ZAI/api_key }}'
export MIMO_API_KEY='{{ pass://API/Mimo/api_key }}'
export TAVILY_API_KEY='{{ pass://API/Tavily/api_key }}'
