#!/bin/bash
if command -v tmux &>/dev/null \
  && [[ $- == *i* ]] \
  && [ -t 0 ] \
  && [[ "$(tty)" == /dev/pts/* ]] \
  && [ -z "$TMUX" ] \
  && [ -z "$VSCODE_RESOLVING_ENVIRONMENT" ]; then
  if tmux has-session -t main 2>/dev/null; then
    exec tmux new-session -t main \; new-window
  else
    exec tmux new-session -s main
  fi
fi
