export EXA_API_KEY='{{ pass://API/Exa/API Key }}'
export CONTEXT7_API_KEY='{{ pass://API/Context7/API Key }}'
export MINIMAX_API_KEY='{{ pass://API/MiniMax/API Key }}'
export ZAI_API_KEY='{{ pass://API/ZAI/API Key }}'
export MIMO_API_KEY='{{ pass://API/Mimo/API Key }}'
export CODESTRAL_API_KEY='{{ pass://API/Codestral/API Key }}'
export MISTRAL_API_KEY='{{ pass://API/Mistral/API Key }}'
export OLLAMA_API_KEY='{{ pass://API/ollama/API Key }}'
